add: addChat/configRaffle; fix: winnerMessage/raffleMessage
backmeupplz/randymbot pull request #34
Opened 2022-01-15 14:42 UTC by sodapng

- Настроены команды addChat и configRaffle
- Обработка исключения бота из чата или канала.
- Исправлены команды winnerMessage и raffleMessage для каналов

2022-01-15 15:43 UTC, backmeupplz requested changes

2022-01-15 15:43 UTC, backmeupplz commented on locales/en.yaml
> +now_editing_this_private_chat: Отлично! Теперь вы редактируете настройки этого чата.
Great! Now you're configuring this chat.

2022-01-15 15:43 UTC, backmeupplz commented on locales/en.yaml
> +now_editing_this_chat: Отлично! Теперь вы редактируете настройки этого чата ${chat}.
Great! Now you're configuring this chat: ${chat}.

2022-01-15 15:43 UTC, backmeupplz commented on locales/ru.yaml
> +now_editing_this_chat: Отлично! Теперь вы редактируете настройки этого чата.
Отличается от en

2022-01-15 15:43 UTC, backmeupplz commented on src/models/Chat.ts
> +  creatorId?: number
Скорее всего, это не нужно

2022-01-15 15:43 UTC, backmeupplz commented on src/helpers/deregisterAdminChatIds.ts
> +  console.log('Я тут!')
Не пушь лишние `console.log` в PR

2022-01-15 15:43 UTC, backmeupplz commented on src/app.ts
> +    .filter(matchFilter('my_chat_member'))
Сверху — миддлвари для всех последующих запросов. Хочешь сделать фильтр — делай его отдельно

2022-01-15 15:43 UTC, backmeupplz commented on src/app.ts
> +    .filter(statusEqAdm, addAdminChatIds)
Вместо этого, стоит просто запрашивать и проверять `getChatMember`, чтобы лишний раз не запоминать админов. Мы не так часто будем запрашивать статус мембера — поэтому это ок.

2022-01-15 15:43 UTC, backmeupplz commented on src/filters/gotKickedMe.ts
> +export default function gotKickedMe(ctx: Context) {
`onlyKickedMe`

2022-01-15 15:43 UTC, backmeupplz commented on src/filters/gotKickedMe.ts
> +  return ctx.myChatMember?.new_chat_member.status === 'left'
Какие еще статусы есть? Мб `kicked` или `restricted`?

2022-01-15 15:43 UTC, backmeupplz commented on src/app.ts
> +  // Bot is excluded from a group or channel
`removed`

2022-01-15 15:43 UTC, backmeupplz commented on src/helpers/deregisterAdminChatIds.ts
> +export default async function deregisterAdminChatIds(ctx: Context) {
`removeChatFromConfigurableChats`

2022-01-15 15:43 UTC, backmeupplz commented on src/helpers/deregisterAdminChatIds.ts
> +
Используй mongo query с `$pull`, чтобы убрать `ctx.chat.id` из `adminChatIds` всех пользователей, у которых он есть.

2022-01-15 15:43 UTC, backmeupplz commented on src/handlers/configRaffle.ts
> +    return
А у нас есть middleware типа `onlyPrivateChats`?

2022-01-15 15:43 UTC, backmeupplz commented on src/handlers/configRaffle.ts
> +    return
Если нет, давай сделаем

2022-01-15 15:43 UTC, backmeupplz commented on src/handlers/configRaffle.ts
> +  const me = await ctx.getChat()
Это же `chat`, а не `me`. `me` — это сам бот

2022-01-15 15:43 UTC, backmeupplz commented on src/handlers/configRaffle.ts
> +      return
Лучше ответь ошибкой

2022-01-15 15:43 UTC, backmeupplz commented on src/helpers/setEditedChat.ts
> +    return
Стоит ответить ошибкой

2022-01-15 15:43 UTC, backmeupplz commented on src/app.ts
> +  //
`// Inline menu callbacks`

2022-01-15 15:43 UTC, backmeupplz commented on src/middlewares/checkEditedChatId.ts
> +export default function checkEditedChatId(ctx: Context, next: NextFunction) {
`onlyWithEditedChatId`

2022-01-15 17:32 UTC, sodapng commented on src/filters/gotKickedMe.ts
> +  return ctx.myChatMember?.new_chat_member.status === 'left'
https://core.telegram.org/bots/api#chatmemberbanned

`kicked` присутствует только в `old_chat_member.status` - старое состояние, необходимое для определения того, что `member` был когда-то в чате/канале.

2022-01-15 18:27 UTC, sodapng commented on src/handlers/configRaffle.ts
> +      return
У `private chat` отсутствует свойство `title`
Если не проверять тип, то будет выдавать ошибку:
`Свойство "title" не существует в типе "PrivateGetChat".`

2022-01-15 20:14 UTC, sodapng commented on src/filters/gotKickedMe.ts
> +  return ctx.myChatMember?.new_chat_member.status === 'left'
Оказывается для `type channel status === left, для type group/supergroup status === kicked`. Хотя условие `ctx.myChatMember?.new_chat_member.status === 'left'` работало и для группы.

2022-01-15 20:22 UTC, sodapng commented on src/app.ts
> +    .filter(statusEqAdm, addAdminChatIds)
Здесь я пытался добавлять `ctx.chat.id` в `adminChatIds`.
Уже исправил на:
```
import { findOrCreateChat } from '@/models/Chat'
import Context from '@/models/Context'

export default async function addAdminChatIds(ctx: Context) {
  if (!ctx.chat || !ctx.from) return

  const { doc: chat } = await findOrCreateChat(ctx.from.id)

  chat.adminChatIds.push(ctx.chat.id)
  return chat.save()
}
```
Может быть реализовать это внутри `middleware attachChat`?

2022-01-16 12:41 UTC, sodapng commented on src/filters/onlyKickedMe.ts
> +  console.log(ctx.myChatMember?.new_chat_member.status)
Исправлю в следующем PR.

2022-01-16 12:43 UTC, sodapng commented on src/middlewares/botRemovedFromAdminChatIds.ts
> +  ctx.chatId = ctx.callbackQuery?.data?.replace('chat:', '')
Это чтобы не дублировать код в `src/helpers/setEditedChat.ts`

2022-01-16 16:03 UTC, backmeupplz requested changes

2022-01-16 16:03 UTC, backmeupplz commented on src/models/Chat.ts
> +export function updateAdminChatIds(chatId: number) {
Ты делаешь `delete`, а не `update`

2022-01-16 16:03 UTC, backmeupplz commented on src/models/Chat.ts
> +    {},
Найди чаты, где `{ adminChatIds: chatId }`, а не делай апдейт всем чатам

2022-01-16 16:03 UTC, backmeupplz commented on src/models/Chat.ts
> +      editedChatId: { $eq: chatId },
`$eq` можно опустить, он подразумевается же

2022-01-16 20:33 UTC, backmeupplz requested changes

2022-01-16 20:33 UTC, backmeupplz commented on src/models/Chat.ts
> +      $unset: { editedChatId: '' },
Тут должен быть `1` или хотя бы `true`

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/configRaffle.ts
> +  for (let i = 0; i < ctx.dbchat.adminChatIds.length; i++) {
Используй тут `for of` (`for (const chatId of ctx.dbchat.adminChatIds) {}`)

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/configRaffle.ts
> +    if (chat.type === 'private') return
Здесь нужно показать пользователю ошибку, а не просто молча заканчивать выполнение функции

2022-01-16 20:33 UTC, backmeupplz commented on src/filters/onlyRepliesToBots.ts
>  export default function onlyRepliesToBots(ctx: Context) {
`onlyRepliesToBotsOrChannelPosts`

2022-01-16 20:33 UTC, backmeupplz commented on src/filters/onlyKickedMe.ts
> +export default function onlyKickedMe(ctx: Context) {
`onlyKickedOrRemovedAdminMe`

2022-01-16 20:33 UTC, backmeupplz commented on src/app.ts
> +    // Middlewares
Лишнее изменение

2022-01-16 20:33 UTC, backmeupplz commented on src/app.ts
> +  // Added
`// Added bot as admin`

2022-01-16 20:33 UTC, backmeupplz commented on src/app.ts
> +  // Removed
`// Kicked or removed bot`

2022-01-16 20:33 UTC, backmeupplz commented on src/middlewares/onlyWithEditedChatId.ts
> +export default function onlyWithEditedChatId(ctx: Context, next: NextFunction) {
`onlyWithEditedChatIdOrPublicChat`

2022-01-16 20:33 UTC, backmeupplz commented on src/app.ts
> -    // Extra middleware
Лишнее изменение

2022-01-16 20:33 UTC, backmeupplz commented on src/filters/onlyIfBotDesignatedAdmin.ts
> +    ctx.myChatMember?.new_chat_member.status === 'administrator' &&
Только если бот был админом — и его снова сделали админом?

2022-01-16 20:33 UTC, backmeupplz commented on src/helpers/addChatFromConfigurableChats.ts
> +export default async function addChatFromConfigurableChats(ctx: Context) {
`AddChatToAdminChatIds`

2022-01-16 20:33 UTC, backmeupplz commented on src/models/Chat.ts
> +export function deleteAdminChatIds(chatId: number) {
`deleteFromAdminChatIds`

2022-01-16 20:33 UTC, backmeupplz commented on src/models/Chat.ts
> +export function deleteEditedChatId(chatId: number) {
`deleteFromEditedChatId`

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/addChat.ts
> +    return
Верни ошибку, если нет `ctx.match`

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/addChat.ts
> +    chat = await ctx.api.getChat(`-${ctx.match}`)
А если закинут уже `/addChat -123456`?

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/addChat.ts
> +  let chat: ChatFromGetChat
Лучше сделать через `?`, чтобы тип не нужно было указывать

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/addChat.ts
> +    return
Можно вернуть 21 строку сразу

2022-01-16 20:33 UTC, backmeupplz commented on src/handlers/addChat.ts
> +    await findOrCreateChat(chat.id)
Это ненужная строка

2022-01-16 20:33 UTC, backmeupplz commented on src/middlewares/botRemovedFromAdminChatIds.ts
> +    return ctx.replyWithLocalization('bot_not_admin_chat')
Это надо проверить внутри хендлера коллбека, не нужно это выносить в отдельную мидлварю

2022-01-17 12:00 UTC, sodapng commented on src/filters/onlyIfBotDesignatedAdmin.ts
> +    ctx.myChatMember?.new_chat_member.status === 'administrator' &&
Да. Можно же изменить права (изменение профиля группы, удаление сообщений и т.д.) админов. Если оставить только `ctx.myChatMember?.new_chat_member.status === 'administrator'`, то `chat.id` будет дублироваться в `adminChatIds`.

2022-01-18 17:15 UTC, backmeupplz requested changes

2022-01-18 17:15 UTC, backmeupplz commented on src/helpers/removeChatFromConfigurableChats.ts
> +  if (!ctx.chat) return
Давай мб экспепшн кинем?

2022-01-18 17:15 UTC, backmeupplz commented on src/app.ts
> +  bot.command('chooseChannelToConfigure', onlyPrivateChats, handleConfigRaffle)
Наверное, это должно быть `chooseChatToCongigure`? 🤔 `chooseChatOrChannelToConfigure`?

2022-01-18 17:15 UTC, backmeupplz commented on src/app.ts
> +    .filter(onlyIfBotDesignatedAdmin, AddChatToAdminChatIds)
не стоит функции с большой буквы называть

2022-01-18 17:15 UTC, backmeupplz commented on src/app.ts
> +    .filter(onlyKickedOrRemovedAdminMe, removeChatFromConfigurableChats)
Нужно проверить случай, когда кикнули или лишили необходимых прав

2022-01-18 17:15 UTC, backmeupplz commented on src/app.ts
> +    .filter(onlyIfBotDesignatedAdmin, AddChatToAdminChatIds)
Нужно проверить случай, когда добавили админом с достаточными правами или когда выдали достаточно прав

2022-01-18 17:15 UTC, backmeupplz commented on src/handlers/addChat.ts
> +  if (!chat) return
Нужно юзеру показать ошибку, не надо молчать

2022-01-18 17:15 UTC, backmeupplz commented on src/handlers/addChat.ts
> +  if (chatMember.status !== 'administrator') {
Нужно проверить, достаточно ли прав

2022-01-18 17:15 UTC, backmeupplz commented on src/helpers/AddChatToAdminChatIds.ts
> +export default async function AddChatToAdminChatIds(ctx: Context) {
Я так понял, ты добавляешь бота в конфигурируемые чаты пользователю, когда пользователь дает админку боту? Хороший ход

2022-01-19 19:38 UTC, sodapng commented on src/helpers/removeChatFromConfigurableChats.ts
> +  if (!ctx.chat) return
Добавил! Можно узнать, зачем мы это делаем? Мы заранее подстраховываемся, если что-то пойдет не так?

2022-01-20 03:18 UTC, backmeupplz requested changes

2022-01-20 03:18 UTC, backmeupplz commented on src/helpers/getChatIdFromCallbackQuery.ts
> +  const chatId = ctx.callbackQuery?.data?.replace('chat:', '')
Давай вот тут сразу конвертнем id: `... = +ctx.callbackQuery?.data?.replace('chat:', '')`

2022-01-20 03:18 UTC, backmeupplz commented on src/helpers/getChatIdFromCallbackQuery.ts
> +  return Number(chatId)
А вот тут давай проверим, не `NaN` ли `chatId`, если `NaN`, то кинем эксепшен

2022-01-20 03:18 UTC, backmeupplz commented on src/filters/onlyIfBotDesignatedAdmin.ts
> +export default function onlyIfBotDesignatedAdmin(ctx: Context) {
`onlyIfGotEnoughPermissions`

2022-01-20 03:18 UTC, backmeupplz commented on src/helpers/AddChatToAdminChatIds.ts
> +import { addChatIdFromAdminChatIds, findOrCreateChat } from '@/models/Chat'
Имя файла тоже нужно написать с маленькой буквы. А потом `git rm -r --cached . && git add .`

2022-01-20 03:18 UTC, backmeupplz commented on src/helpers/setEditedChat.ts
> +  if (ctx.me.id !== chatId && !ctx.dbchat.adminChatIds.includes(chatId)) {
`adminChatIds` — это список айди чатов, которые человек (в приватном чате) может конфигурировать. Проверять тут нужно через `getChatMember` бота, является ли он все еще админом. Если нет — кинуть ошибку и убрать чат из `adminChatIds`

2022-01-20 03:18 UTC, backmeupplz commented on src/handlers/addChat.ts
> +    const chatId = regExUsernameOrId.exec(`${ctx.match}`)
Этот хак с превращением `ctx.match` обязателен? Это же и так должна быть строка?

2022-01-20 03:18 UTC, backmeupplz commented on src/handlers/addChat.ts
> +
Давай еще проверим права человека, который вызывает эту команду

2022-01-20 10:54 UTC, sodapng commented on src/handlers/addChat.ts
> +    const chatId = regExUsernameOrId.exec(`${ctx.match}`)
`(property) Context.match?: string | RegExpMatchArray | undefined`

2022-01-21 17:01 UTC, backmeupplz requested changes

2022-01-21 17:01 UTC, backmeupplz commented on src/handlers/addChat.ts
> +    const { status: isChatAdmin } = await ctx.api.getChatMember(
Не `isChatAdmin`, а `userChatMemberStatus`

2022-01-21 17:01 UTC, backmeupplz commented on src/helpers/setEditedChat.ts
> +  const { status: isNotAdmin } = await ctx.api.getChatMember(
Это `userChatMemberStatus`

2022-01-22 15:08 UTC, merged